language: d
d:
  - dmd
  - gdc
  - ldc

script: ./travis.sh

sudo: false
addons:
  apt:
    packages:
    - gdb

env:
  - SELF_COMPILE=0
  - SELF_COMPILE=2

matrix:
  include:
    - os: osx
      d: dmd-beta
      env: SELF_COMPILE=0
